version: '3.8'

services:
  code-executor:
    build: .
    ports:
      - "8080:8080"   # REST API
      - "50051:50051" # gRPC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE  # Required for Docker socket access
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
